create or replace PACKAGE PKG_ACH_CONST IS
   /* Khai bao chung */
   ACH_OUT_SERVICE_NAME VARCHAR2(10) := 'ACH_OUT';

   ACH_IN_SERVICE_NAME VARCHAR2(10) := 'ACH_IN';

   ACH_CCY_VND VARCHAR2(20) := 'VND';

   ACH_DATE_LIMIT_UPDATE INTEGER := 200;

   STATUS_ACTIVE     VARCHAR2(10) := 'A';
   STATUS_PROCESSING VARCHAR2(10) := 'P';
   STATUS_CLOSED     VARCHAR2(10) := 'C';

   /*Ma loi validate*/
   COMMON_PAYMENT_LIMIT_TIME CONSTANT VARCHAR(20) := '28'; --Loi qua thoi gian cho phep voi giao dich chuyen tien

   COMMON_TRANS_COINCIDES_XREF CONSTANT VARCHAR(20) := '30'; --DUPLICATE XREF

   COMMON_TRANS_COINCIDES_ELEMENT CONSTANT VARCHAR(20) := '31'; --DUPLICATE ELEMENT

   COMMON_AMOUNT_INVALID CONSTANT VARCHAR(20) := '32'; -- sai dinh dang tien

   COMMON_MONEYTYPE_INVALID CONSTANT VARCHAR(20) := '33'; -- sai dinh dang loai tien VND

   COMMON_AMOUNT_LIMIT_ERR CONSTANT VARCHAR(20) := '34'; -- han muc

   TRANS_ACC_CLOSED CONSTANT VARCHAR(20) := '35';

   COMMON_ACC_NO_DR CONSTANT VARCHAR(20) := '36'; -- Cam ghi no

   COMMON_ACC_NO_CR CONSTANT VARCHAR(20) := '37'; -- cam ghi co

   COMMON_ACC_INVALID CONSTANT VARCHAR(20) := '38'; -- khong thoa man

   TRANS_ACC_LOCKED CONSTANT VARCHAR(20) := '39'; --tk bi khoa

   TRANS_ACC_BLACKLIST CONSTANT VARCHAR(20) := '40'; -- TK trong danh sach den

   COMMON_SOU_ACC_NOT_ENOU_USAGE CONSTANT VARCHAR(20) := '41'; --TAI KHOAN khong du

   TRANS_ACC_NOT_EXIST CONSTANT VARCHAR(20) := '42'; -- tai khoan khong ton tai

   COMMON_CARD_INACTIVE CONSTANT VARCHAR(20) := '43'; --the BI LOI

   COMMON_CARD_INVALID CONSTANT VARCHAR(20) := '44'; --the khong ton tai

   COMMON_FORMAT_INVALID CONSTANT VARCHAR(20) := '45'; -- Khong dung dinh dang

   COMMON_PHONENUMBER_NOT_SUPPORT CONSTANT VARCHAR(20) := '46'; -- sdt khong dc ho tro

   COMMON_CARD_EXPIRED CONSTANT VARCHAR(20) := '47'; --THE HET HAN OK

   COMMON_TRANS_NOT_SUPPORTED CONSTANT VARCHAR(20) := '48'; -- giao dich khong duoc ho tro

   COMMON_AMOUNT_INVALID_PER_DAY CONSTANT VARCHAR(20) := '49'; -- han muc giao dich trong ngay

   COMMON_EMPTY_ERR CONSTANT VARCHAR(20) := '50'; --LOI du lieu de trong

   COMMON_OTHER_VALIDATE_ERR CONSTANT VARCHAR(20) := '51'; --LOI cho cac truong hop khac

   /* he thong*/
   COMMON_TRANS_NOTFOUND CONSTANT VARCHAR(20) := 'NOTFOUND';

   COMMON_TRANS_SUCCESS CONSTANT VARCHAR(20) := '00';

   COMMON_NOT_REVERSE CONSTANT VARCHAR(20) := '0';

   COMMON_TRANS_FAILED CONSTANT VARCHAR(20) := '96';

   COMMON_TRANS_EXCEPTION CONSTANT VARCHAR(20) := '68'; --LOI khong xac dinh

   BRACH_HO CONSTANT VARCHAR2(50) := '000';

   /*ACH PACS*/
   ACH_PACS_008 CONSTANT VARCHAR(20) := 'pacs.008.001.07';
   ACH_PACS_004 CONSTANT VARCHAR(20) := 'pacs.004.001.08';
   ACH_CAMT_010 CONSTANT VARCHAR(20) := 'camt.010.001.07';



END PKG_ACH_CONST;
